- id: '1747507750285'
  alias: Turn on Bathroom Mirror when Motion is detected
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.bathroom_motion
      light_target:
        entity_id: light.bathroom_mirror
